spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/schedule_db?serverTimezone=JST
    username: root
    password: HmTr__0612
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
